DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS favourites CASCADE;
DROP TABLE IF EXISTS activities CASCADE;
DROP TABLE IF EXISTS plans CASCADE;
DROP TABLE IF EXISTS time_slots CASCADE;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO vagrant;
CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  full_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE activities (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  address VARCHAR(255) NOT NULL,
  types VARCHAR(255) NOT NULL
);

CREATE TABLE plans (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  date DATE NOT NULL,
  active SMALLINT NOT NULL DEFAULT 0,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE time_slots (
  id SERIAL PRIMARY KEY NOT NULL,
  start_time SMALLINT NOT NULL DEFAULT 0,
  end_time SMALLINT NOT NULL DEFAULT 0,
  activity_id INTEGER REFERENCES activities(id) ON DELETE CASCADE,
  plan_id INTEGER REFERENCES plans(id) ON DELETE CASCADE
);

CREATE TABLE favourites (
  id SERIAL PRIMARY KEY NOT NULL,
  is_favourite SMALLINT NOT NULL DEFAULT 0,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  activity_id INTEGER REFERENCES activities(id) ON DELETE CASCADE
);